-- ==================================================
-- SUPABASE DATABASE SCHEMA
-- Project: SumutCluster
-- ==================================================

create extension if not exists pgcrypto;

create table if not exists public.admins (
id uuid primary key default gen_random_uuid(),
name text not null,
username text not null unique,
password_hash text not null,
created_at timestamp with time zone default now(),
updated_at timestamp with time zone default now()
);

create table if not exists public.tourism_data (
id bigint generated by default as identity primary key,
kabupaten_kota text not null,
destinasi_wisata text not null,
tahun int not null,
bulan text not null,
jumlah_kunjungan int not null default 0,
musim_libur int not null default 0,
libur_nasional int not null default 0,
created_at timestamp with time zone default now(),
updated_at timestamp with time zone default now()
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
new.updated_at = now();
return new;
end;
$$ language plpgsql;

drop trigger if exists set_admins_updated_at on public.admins;
create trigger set_admins_updated_at
before update on public.admins
for each row
execute function public.set_updated_at();

drop trigger if exists set_tourism_data_updated_at on public.tourism_data;
create trigger set_tourism_data_updated_at
before update on public.tourism_data
for each row
execute function public.set_updated_at();

create index if not exists idx_tourism_data_tahun on public.tourism_data(tahun);
create index if not exists idx_tourism_data_kabupaten on public.tourism_data(kabupaten_kota);
create index if not exists idx_tourism_data_destinasi on public.tourism_data(destinasi_wisata);
create index if not exists idx_tourism_data_bulan on public.tourism_data(bulan);
create unique index if not exists idx_tourism_data_unique_record
on public.tourism_data(kabupaten_kota, destinasi_wisata, tahun, bulan, jumlah_kunjungan, musim_libur, libur_nasional);

alter table public.admins enable row level security;
alter table public.tourism_data enable row level security;

drop policy if exists "Public can read tourism data" on public.tourism_data;
drop policy if exists "Service role can manage tourism data" on public.tourism_data;
drop policy if exists "Service role can read admins" on public.admins;
drop policy if exists "Service role can manage admins" on public.admins;

create policy "Public can read tourism data"
on public.tourism_data
for select
to anon, authenticated
using (true);

create policy "Service role can manage tourism data"
on public.tourism_data
for all
to service_role
using (true)
with check (true);

create policy "Service role can read admins"
on public.admins
for select
to service_role
using (true);

create policy "Service role can manage admins"
on public.admins
for all
to service_role
using (true)
with check (true);

grant usage on schema public to anon, authenticated, service_role;
grant select on public.tourism_data to anon, authenticated;
grant select, insert, update, delete on public.tourism_data to service_role;
grant select, insert, update, delete on public.admins to service_role;
grant usage, select on sequence public.tourism_data_id_seq to anon, authenticated, service_role;
